/*
 * generated by Xtext 2.13.0
 */
package org.svis.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CityStandaloneSetup extends CityStandaloneSetupGenerated {

	def static void doSetup() {
		new CityStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
