/*
 * generated by Xtext 2.13.0
 */
package org.svis.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DynamixStandaloneSetup extends DynamixStandaloneSetupGenerated {

	def static void doSetup() {
		new DynamixStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
