/*
 * generated by Xtext 2.9.0.rc2
 */
package org.svis.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PlantRuntimeModule extends AbstractPlantRuntimeModule {
}
