source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'

# Use sqlite3 as the database for Active Record
#gem 'sqlite3'
gem 'mysql2'
#gem "pg"

# Use SCSS for stylesheets
gem 'sass-rails'#, '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'#, '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'#, '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platforms => :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'#, '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', :require => false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby'#, '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', :group => :development

# Use debugger
# gem 'debugger', :group => [:development, :test]

# gem 'bootstrap-sass'
# group :development do
#   gem 'rails_layout'
# end


group :development do
  gem 'listen'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'database_cleaner'
  gem "i18n-tasks"
  gem 'capybara'
  gem 'simplecov', require: false
  gem 'brakeman', require: false
  gem 'capybara-screenshot', :group => :test
end


gem "font-awesome-rails"
gem "therubyracer"
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem 'bootstrap-sass'
gem "paperclip"
gem "nokogiri"
gem "rubyzip"
gem "actionmailer"
#gem "jquery-sortable-rails"
gem "ranked-model"
gem "acts_as_list"
gem "tinymce-rails"
gem 'bootstrap-multiselect-rails4'
#gem 'rails_12factor'
gem 'rails_serve_static_assets'
#gem 'rails_stdout_logging'
gem "cocoon"
gem 'multi-select-rails'
gem "puma"


group :development do
  gem 'seed_dump'
end

gem 'bundler-audit'
