/*
 * generated by Xtext 2.13.0
 */
package org.svis.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GraphStandaloneSetup extends GraphStandaloneSetupGenerated {

	def static void doSetup() {
		new GraphStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
