/*
 * generated by Xtext 2.13.0
 */
package org.svis.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GraphRuntimeModule extends AbstractGraphRuntimeModule {
}
