/*
 * generated by Xtext 2.9.0.rc2
 */
package org.svis.xtext.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CityValidator extends AbstractCityValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					CityPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
